name: Test and Update dist

on:
  pull_request:
    branches: [master]
  workflow_dispatch:

permissions: {}

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Set up Repository
        uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3

      - name: Get Node Version
        id: node_version
        run: |
          node_version=`cat .nvmrc`
          echo "::set-output name=node_version::$node_version"
          echo "Node Version: $node_version"

      - name: Set up Node
        uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3
        with:
          node-version: ${{ steps.node_version.outputs.node_version }}

      - name: Cache NPM Dependencies
        id: cache-npm-dependencies
        uses: actions/cache@8492260343ad570701412c2f464a5877dc76bace # v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-

      - name: Install NPM Dependencies if not cached
        if: steps.cache-npm-dependencies.outputs.cache-hit != 'true'
        run: |
          npm install

      - name: Build Action
        run: npm run build

      - name: Lint Action
        run: npm run lint

      - name: Test Action
        run: npm run test

      - name: Package Action
        run: npm run package

      - name: Commit if dist has changed
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          PR_HEAD_REF: ${{ github.event.pull_request.head.ref }}
        run: |
          printf "%s\n" "$GITHUB_CONTEXT"
          git config user.name "Github Actions"
          git config user.email noreply@github.com
          if [ $(git status dist --porcelain=v1 2>/dev/null | wc -l) != "0" ]; then
            git add dist
            git commit -m "chore: updated dist with new code"
            git push origin HEAD:"$PR_HEAD_REF" --force
          fi
